// <auto-generated />
using System;
using DemoProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DemoProject.Migrations
{
    [DbContext(typeof(DemoProjectContext))]
    [Migration("20261001132717_restrictRelationships")]
    partial class restrictRelationships
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DemoProject.Models.Bestelling", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("KlantId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KlantId");

                    b.ToTable("Bestelling", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            KlantId = 1
                        },
                        new
                        {
                            Id = 2,
                            KlantId = 1
                        },
                        new
                        {
                            Id = 3,
                            KlantId = 2
                        },
                        new
                        {
                            Id = 4,
                            KlantId = 3
                        },
                        new
                        {
                            Id = 5,
                            KlantId = 4
                        },
                        new
                        {
                            Id = 6,
                            KlantId = 5
                        },
                        new
                        {
                            Id = 7,
                            KlantId = 6
                        },
                        new
                        {
                            Id = 8,
                            KlantId = 7
                        },
                        new
                        {
                            Id = 9,
                            KlantId = 8
                        },
                        new
                        {
                            Id = 10,
                            KlantId = 10
                        });
                });

            modelBuilder.Entity("DemoProject.Models.Klant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AchterNaam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("DatumAangemaakt")
                        .HasColumnType("date");

                    b.Property<string>("Voornaam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Klant", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AchterNaam = "Janssens",
                            DatumAangemaakt = new DateOnly(2023, 1, 15),
                            Voornaam = "Jan"
                        },
                        new
                        {
                            Id = 2,
                            AchterNaam = "Peeters",
                            DatumAangemaakt = new DateOnly(2023, 2, 20),
                            Voornaam = "Sophie"
                        },
                        new
                        {
                            Id = 3,
                            AchterNaam = "Maes",
                            DatumAangemaakt = new DateOnly(2023, 4, 10),
                            Voornaam = "Lucas"
                        },
                        new
                        {
                            Id = 4,
                            AchterNaam = "Jacobs",
                            DatumAangemaakt = new DateOnly(2023, 5, 2),
                            Voornaam = "Emma"
                        },
                        new
                        {
                            Id = 5,
                            AchterNaam = "Willems",
                            DatumAangemaakt = new DateOnly(2023, 6, 18),
                            Voornaam = "Liam"
                        },
                        new
                        {
                            Id = 6,
                            AchterNaam = "Mertens",
                            DatumAangemaakt = new DateOnly(2023, 7, 22),
                            Voornaam = "Olivia"
                        },
                        new
                        {
                            Id = 7,
                            AchterNaam = "Claes",
                            DatumAangemaakt = new DateOnly(2023, 8, 30),
                            Voornaam = "Noah"
                        },
                        new
                        {
                            Id = 8,
                            AchterNaam = "Goossens",
                            DatumAangemaakt = new DateOnly(2023, 9, 14),
                            Voornaam = "Ella"
                        },
                        new
                        {
                            Id = 9,
                            AchterNaam = "Wouters",
                            DatumAangemaakt = new DateOnly(2023, 11, 5),
                            Voornaam = "Arthur"
                        },
                        new
                        {
                            Id = 10,
                            AchterNaam = "De Smet",
                            DatumAangemaakt = new DateOnly(2024, 1, 12),
                            Voornaam = "Mila"
                        });
                });

            modelBuilder.Entity("DemoProject.Models.Laptop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GPU")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Merk")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Processor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RamInGB")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Laptop", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GPU = "RTX 3050",
                            Merk = "Acer",
                            Price = 699m,
                            Processor = "Intel I7",
                            RamInGB = 16
                        },
                        new
                        {
                            Id = 2,
                            GPU = "RTX 4060",
                            Merk = "ASUS",
                            Price = 1299m,
                            Processor = "Intel i7",
                            RamInGB = 16
                        },
                        new
                        {
                            Id = 3,
                            GPU = "RTX 3060",
                            Merk = "Lenovo",
                            Price = 899m,
                            Processor = "AMD Ryzen 7",
                            RamInGB = 16
                        },
                        new
                        {
                            Id = 4,
                            GPU = "Integrated",
                            Merk = "HP",
                            Price = 549m,
                            Processor = "Intel i5",
                            RamInGB = 8
                        },
                        new
                        {
                            Id = 5,
                            GPU = "RTX 4070",
                            Merk = "MSI",
                            Price = 1899m,
                            Processor = "Intel i9",
                            RamInGB = 32
                        },
                        new
                        {
                            Id = 6,
                            GPU = "M3 10-core",
                            Merk = "Apple",
                            Price = 1499m,
                            Processor = "Apple M3",
                            RamInGB = 16
                        },
                        new
                        {
                            Id = 7,
                            GPU = "RTX 3050 Ti",
                            Merk = "Dell",
                            Price = 1099m,
                            Processor = "Intel i7",
                            RamInGB = 16
                        },
                        new
                        {
                            Id = 8,
                            GPU = "RTX 4080",
                            Merk = "Gigabyte",
                            Price = 2199m,
                            Processor = "AMD Ryzen 9",
                            RamInGB = 32
                        },
                        new
                        {
                            Id = 9,
                            GPU = "Integrated",
                            Merk = "Acer",
                            Price = 429m,
                            Processor = "AMD Ryzen 3",
                            RamInGB = 8
                        },
                        new
                        {
                            Id = 10,
                            GPU = "RTX 4090",
                            Merk = "Razer",
                            Price = 2799m,
                            Processor = "Intel i9",
                            RamInGB = 32
                        });
                });

            modelBuilder.Entity("DemoProject.Models.OrderLijn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Aantal")
                        .HasColumnType("int");

                    b.Property<int>("BestellingId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BestellingId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderLijn", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Aantal = 1,
                            BestellingId = 1,
                            ProductId = 1
                        },
                        new
                        {
                            Id = 2,
                            Aantal = 2,
                            BestellingId = 1,
                            ProductId = 5
                        },
                        new
                        {
                            Id = 3,
                            Aantal = 5,
                            BestellingId = 2,
                            ProductId = 3
                        },
                        new
                        {
                            Id = 4,
                            Aantal = 1,
                            BestellingId = 3,
                            ProductId = 2
                        },
                        new
                        {
                            Id = 5,
                            Aantal = 2,
                            BestellingId = 3,
                            ProductId = 6
                        },
                        new
                        {
                            Id = 6,
                            Aantal = 1,
                            BestellingId = 4,
                            ProductId = 4
                        },
                        new
                        {
                            Id = 7,
                            Aantal = 1,
                            BestellingId = 5,
                            ProductId = 10
                        },
                        new
                        {
                            Id = 8,
                            Aantal = 1,
                            BestellingId = 6,
                            ProductId = 7
                        },
                        new
                        {
                            Id = 9,
                            Aantal = 3,
                            BestellingId = 7,
                            ProductId = 8
                        },
                        new
                        {
                            Id = 10,
                            Aantal = 1,
                            BestellingId = 8,
                            ProductId = 9
                        },
                        new
                        {
                            Id = 11,
                            Aantal = 10,
                            BestellingId = 9,
                            ProductId = 3
                        },
                        new
                        {
                            Id = 12,
                            Aantal = 1,
                            BestellingId = 10,
                            ProductId = 1
                        });
                });

            modelBuilder.Entity("DemoProject.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Beschrijving")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Prijs")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Product", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Beschrijving = "Allround workstation",
                            Naam = "Laptop",
                            Prijs = 999.00m
                        },
                        new
                        {
                            Id = 2,
                            Beschrijving = "Krachtige desktop-computer",
                            Naam = "Pc",
                            Prijs = 1299.49m
                        },
                        new
                        {
                            Id = 3,
                            Beschrijving = "Spuitbus voor stofreiniging",
                            Naam = "Perslucht",
                            Prijs = 14.99m
                        },
                        new
                        {
                            Id = 4,
                            Beschrijving = "RGB gaming toetsenbord",
                            Naam = "Mechanisch Toetsenbord",
                            Prijs = 89.95m
                        },
                        new
                        {
                            Id = 5,
                            Beschrijving = "Ergonomische optische muis",
                            Naam = "Draadloze Muis",
                            Prijs = 34.50m
                        },
                        new
                        {
                            Id = 6,
                            Beschrijving = "4K Ultra HD IPS scherm",
                            Naam = "27 inch Monitor",
                            Prijs = 329.00m
                        },
                        new
                        {
                            Id = 7,
                            Beschrijving = "Noise-cancelling gaming headset",
                            Naam = "Headset",
                            Prijs = 79.99m
                        },
                        new
                        {
                            Id = 8,
                            Beschrijving = "7-in-1 adapter met HDMI",
                            Naam = "USB-C Hub",
                            Prijs = 45.00m
                        },
                        new
                        {
                            Id = 9,
                            Beschrijving = "Full HD webcam met microfoon",
                            Naam = "Webcam 1080p",
                            Prijs = 59.90m
                        },
                        new
                        {
                            Id = 10,
                            Beschrijving = "Snelle USB 3.2 draagbare schijf",
                            Naam = "Externe SSD 1TB",
                            Prijs = 112.50m
                        });
                });

            modelBuilder.Entity("DemoProject.Models.Bestelling", b =>
                {
                    b.HasOne("DemoProject.Models.Klant", "Klant")
                        .WithMany("Bestellingen")
                        .HasForeignKey("KlantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Klant");
                });

            modelBuilder.Entity("DemoProject.Models.OrderLijn", b =>
                {
                    b.HasOne("DemoProject.Models.Bestelling", "Bestelling")
                        .WithMany("Orderlijnen")
                        .HasForeignKey("BestellingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DemoProject.Models.Product", "Product")
                        .WithMany("OrderLijnen")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bestelling");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("DemoProject.Models.Bestelling", b =>
                {
                    b.Navigation("Orderlijnen");
                });

            modelBuilder.Entity("DemoProject.Models.Klant", b =>
                {
                    b.Navigation("Bestellingen");
                });

            modelBuilder.Entity("DemoProject.Models.Product", b =>
                {
                    b.Navigation("OrderLijnen");
                });
#pragma warning restore 612, 618
        }
    }
}
