// <auto-generated />
using DemoProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DemoProject.Migrations
{
    [DbContext(typeof(DemoProjectContext))]
    partial class DemoProjectContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DemoProject.Models.Laptop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GPU")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Merk")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Processor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RamInGB")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Laptop", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GPU = "RTX 3050",
                            Merk = "Acer",
                            Price = 699m,
                            Processor = "Intel I7",
                            RamInGB = 16
                        },
                        new
                        {
                            Id = 2,
                            GPU = "RTX 4060",
                            Merk = "ASUS",
                            Price = 1299m,
                            Processor = "Intel i7",
                            RamInGB = 16
                        },
                        new
                        {
                            Id = 3,
                            GPU = "RTX 3060",
                            Merk = "Lenovo",
                            Price = 899m,
                            Processor = "AMD Ryzen 7",
                            RamInGB = 16
                        },
                        new
                        {
                            Id = 4,
                            GPU = "Integrated",
                            Merk = "HP",
                            Price = 549m,
                            Processor = "Intel i5",
                            RamInGB = 8
                        },
                        new
                        {
                            Id = 5,
                            GPU = "RTX 4070",
                            Merk = "MSI",
                            Price = 1899m,
                            Processor = "Intel i9",
                            RamInGB = 32
                        },
                        new
                        {
                            Id = 6,
                            GPU = "M3 10-core",
                            Merk = "Apple",
                            Price = 1499m,
                            Processor = "Apple M3",
                            RamInGB = 16
                        },
                        new
                        {
                            Id = 7,
                            GPU = "RTX 3050 Ti",
                            Merk = "Dell",
                            Price = 1099m,
                            Processor = "Intel i7",
                            RamInGB = 16
                        },
                        new
                        {
                            Id = 8,
                            GPU = "RTX 4080",
                            Merk = "Gigabyte",
                            Price = 2199m,
                            Processor = "AMD Ryzen 9",
                            RamInGB = 32
                        },
                        new
                        {
                            Id = 9,
                            GPU = "Integrated",
                            Merk = "Acer",
                            Price = 429m,
                            Processor = "AMD Ryzen 3",
                            RamInGB = 8
                        },
                        new
                        {
                            Id = 10,
                            GPU = "RTX 4090",
                            Merk = "Razer",
                            Price = 2799m,
                            Processor = "Intel i9",
                            RamInGB = 32
                        });
                });

            modelBuilder.Entity("DemoProject.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Prijs")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Product", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Naam = "Laptop",
                            Prijs = 999m
                        },
                        new
                        {
                            Id = 2,
                            Naam = "Pc",
                            Prijs = 1299.49m
                        },
                        new
                        {
                            Id = 3,
                            Naam = "Perslucht",
                            Prijs = 14.99m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
